version: "3"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5432:5432"



  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    command: [ "python3", "main.py" ]
